ベクトル式を扱う

- ベクトルを扱うサンプルコードを書いて。

In [1]:
import numpy as np

# Create a vector
vector = np.array([1, 2, 3])

# Print the vector
print("Vector:", vector)

# Calculate the length of the vector
length = np.linalg.norm(vector)
print("Length of the vector:", length)

# Calculate the dot product of two vectors
vector2 = np.array([4, 5, 6])
dot_product = np.dot(vector, vector2)
print("Dot product of the two vectors:", dot_product)

# Calculate the cross product of two vectors
cross_product = np.cross(vector, vector2)
print("Cross product of the two vectors:", cross_product)

Vector: [1 2 3]
Length of the vector: 3.7416573867739413
Dot product of the two vectors: 32
Cross product of the two vectors: [-3  6 -3]


行列を扱う

- 行列を扱うサンプルコードを書いて

In [1]:
import numpy as np

# Create a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the matrix
print("Matrix:")
print(matrix)

# Calculate the transpose of the matrix
transpose = np.transpose(matrix)
print("Transpose of the matrix:")
print(transpose)
# Check if the matrix is singular
if np.linalg.det(matrix) == 0:
    print("Matrix is singular, cannot calculate inverse.")
else:
    # Calculate the inverse of the matrix
    inverse = np.linalg.inv(matrix)
    print("Inverse of the matrix:")
    print(inverse)

print("Matrix multiplication:")
# Create a matrix
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
# Multiply the two matrices
product = np.dot(matrix1, matrix2)
print(product)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix is singular, cannot calculate inverse.
Matrix multiplication:
[[19 22]
 [43 50]]


In [ ]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

# 画像を読み込む
image = cv2.imread('path_to_image.jpg')

# 画像をグレースケールに変換する
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# 輝度を調整する（例：輝度を50増加させる）
adjusted_image = np.clip(gray_image + 50, 0, 255)

# 加工した画像を表示する
plt.imshow(adjusted_image, cmap='gray')
plt.title('Brightness Adjusted Image')
plt.show()